"""empty message

Revision ID: 68328a4bdc6b
Revises: 234b86e3b738
Create Date: 2024-02-07 11:32:58.631534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68328a4bdc6b'
down_revision = '234b86e3b738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_menu_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'food_menus', ['food_menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('food_menu_id')

    # ### end Alembic commands ###
